kind: pipeline
type: docker
name: default

steps:
  - name: denemeSteps
    image: alpine
    commands:
      - echo hello
      - echo world

  - name: denemeSteps
      image: alpine
      commands:
        - echo hello
        - echo world
  - name: denemeStepsss
      image: alpine
      commands:
        - echo hello
        - echo world
