kind: pipeline
type: docker
name: default

steps:
  - name: build-gradlew
    image: androidsdk/android-29
    commands:
      - sdkmanager --update
      - echo no | avdmanager create avd -n test -k "system-images;android-29;google_apis;x86_64"
      - echo y |apt-get install qemu-kvm
      - kvm-ok
      - emulator -avd test -no-window
      - ./gradlew test

  - name: build-android
    image: niltonvasques/android-sdk-and-emulator:0.1.5
    commands:
      - cp -a /drone/.gradle /root/ && rm -Rf /drone/.gradle
      - start_emulator && wait_emulator
      - ./gradlew check --daemon -PdisablePreDex --stacktrace
      - ./gradlew assembleDebugAndroidTest --daemon -PdisablePreDex --stacktrace
      - unlock_emulator
      - ./gradlew cC --daemon -PdisablePreDex --stacktrace
      - cp -a /root/.gradle /drone/
